services:
  backend:
    build: .
    container_name: smartbala-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
#     depends_on:
#       - redis

#   redis:
#     image: redis:8
#     container_name: smartbala-redis
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data
#     restart: always

# volumes:
#   redis_data:
